// src/components/Example.tsx
import React from 'react'
import { Example as ExampleType } from '../types/WordResult'

type SentenceProps = {
  example: ExampleType
}

type ExampleProps = {
  examples: Array<ExampleType>
}

const Sentence = (props: SentenceProps) => {
  return (
    <div className="mb-2">
      <p className="sentence-es">{props.example.example}</p>
      <p className="sentence-en text-gray-700">{props.example.exampleTranslation}</p>
    </div>
  )
}

const Example = (props: ExampleProps) => {
  return (
    <div className="text-lg px-2">
      {
        props.examples.map(example =>
        <Sentence example={example} />)
      }
    </div>
  )
}

export default Example

// src/components/ui/dict/Example.vue
<template>
  <div class="text-lg px-2">
    <div class="mb-2" v-for="(example, index) in examples" :key="index">
      <p class="sentence-es">{{ example.example }}</p>
      <p class="sentence-en text-gray-700">{{ example.exampleTranslation }}</p>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Example',
  props: {
    examples: Array
  }
}
</script>

<style scoped>
.sentence-es::before {
  content: '• '
}

.sentence-en::before {
  content: '- '
}
</style>
