// src/components/Header.tsx
import React from 'react'
import Button from './buttons/Button'
import LanguageSwitcher from './LanguageSwitcher'
import { useHistory } from 'react-router-dom'

const Header = () => {
  let history = useHistory()

  return (
      <header className="flex justify-between text-3xl">
        <div className="flex justify-start">
          <Button icon="🌎" onClick={() => history.push('/')} />
            <LanguageSwitcher />
        </div>

        <div>
          <Button icon="⚙️" />
        </div>
      </header>
  )
}

export default Header

// src/components/layout/Header.vue
<template>
  <div class="flex justify-between text-3xl">
    <div class="flex justify-start">
      <button class="button pr-2" @click="toHome"><span>🌎</span></button>
      <button class="button pr-2"><span>🇪🇸</span></button>
      <button class="button"><span>🇺🇸</span></button>
      <!-- <button class="">🇹🇷</button> -->
    </div>
    <div>
      <button class="button"><span>⚙️</span></button>
    </div>
  </div>
</template>

<script>
export default {
  name: 'Header',
  methods: {
    toHome: function() {
      this.$router.push('/')
    }
  }
}
</script>

<style scoped>
.button:hover {
  @apply underline text-gray-500;
}
.button:focus {
  @apply underline text-gray-800;
}
</style>
