// src/pages/Dict.tsx
import React from 'react'
import { useParams } from 'react-router-dom'
import AudioButton from '../components/buttons/AudioButton'
import Item from '../components/Item'
import LoadingSkeleton from '../components/LoadingSkeleton'
import Logo from '../components/Logo'
import CurrentLanguage from '../containers/CurrentLanguage'
import useWordResult from '../hooks/useWordResult'

const Dict = () => {
  const { query } = useParams<{ query: string }>()
  const { currentLanguage } = CurrentLanguage.useContainer()
  const { wordResult, error } = useWordResult(query, currentLanguage)

  return (
    <div>
      { error && <Logo text="404 NOT FOUND :(" /> }
      { wordResult == null && !error && <LoadingSkeleton />}
      { wordResult && 
        <div>
          <div className="flex justify-between items-center px-2 py-8">
            <div className="flex">
              <span className="text-4xl font-bold text-gray-800 pr-4">
                {wordResult.word}
              </span>
              { wordResult.phonetics &&
                <span className="text-2xl font-bold text-gray-600 self-end">
                  {wordResult.phonetics}
                </span>
              }
            </div>
 
            { wordResult.audioUrl && <AudioButton audioUrl={wordResult.audioUrl} /> }

          </div>

          {wordResult.definitions.map(item =>
            <Item item={item}/>
          )}

        </div>
      }
    </div>
  )
}

export default Dict

// src/views/Dict.vue
<template>
  <div>
    <div v-if="result">
      <div class="flex justify-between items-center px-2 py-8">
        <div class="flex">
          <span class="text-4xl font-bold text-gray-800 pr-4">{{ result.word }}</span>
          <span v-if="result.phonetics" class="text-2xl font-bold text-gray-600 self-end">{{ result.phonetics }}</span>
        </div>
        <span class="text-2xl text-gray-800 hover:text-gray-600">
          <button @click="playAudio">
            <i class="fas fa-play mt-2">
              <audio ref="audio" :src="result.audioUrl"></audio>
            </i>
          </button>
        </span>
      </div>

      <Item
        v-for="(definition, index) in result.definitions"
        :key="index"
        :item="definition"/>
    </div>
    <LoadingSkeleton v-else/>
  </div>
</template>

<script>
import Item from '@/components/ui/dict/Item.vue'
import LoadingSkeleton from '@/components/ui/LoadingSkeleton.vue'

export default {
  name: 'Dict',
  props: {
    query: String
  },
  computed: {
    lang: function() {
      return this.$route.query.lang
    }
  },
  data: function() {
    return {
      result: null
    }
  },
  components: {
    Item,
    LoadingSkeleton
  },
  mounted: function() {
    const apis = {
      es: `https://dictlet.herokuapp.com/spanishdict/query/${this.query}?isPosAbbr=false`,
      en: `https://dictlet.herokuapp.com/youdao-collins/query/${this.query}`,
      tr: `https://dictlet.herokuapp.com/seslisozluk/query/${this.query}`
    }
    fetch(apis[this.lang])
      .then(response => response.json())
      .then(data => {
        if (data.success) {
          this.result = data.result
        } else {
          this.$router.push('/error')
        }
      })
      .catch(() => this.router.push('/error'))
  },
  methods: {
    playAudio: function() {
      this.$refs.audio.play()
    }
  }
}
</script>
