// src/components/ui/dict/Definition.vue
<template>
  <div class="bg-gray-200 p-2 mb-2 text-lg text-gray-800 shadow-sm rounded">
    <span class="definition font-bold pr-2">{{ pos }}</span>
    <span>{{ sense }}</span>
  </div>
</template>

<script>
export default {
 name: 'Definition',
 props: {
   pos: String,
   sense: String
 }
}
</script>

<style scoped>
.definition::before {
  content: '◼ '
}
</style>

// src/components/Definition.tsx
import React from 'react'

type DefinitionProps = {
  pos: string | null,
  sense: string | null
}

const Definition = (props: DefinitionProps) => {
  return (
    <div className="bg-gray-200 p-2 mb-2 text-lg text-gray-800 shadow-sm rounded">
      <span className="definition font-bold pr-2">{props.pos}</span>
      <span>{props.sense}</span>
    </div>
  )
}

export default Definition
