// src/components/ui/dict/Item.vue
<template>
  <div>
    <Definition
      :pos="item.pos"
      :sense="item.sense"
      />
    <Example
      :examples="item.examples"
      />
  </div>
</template>

<script>
import Definition from '@/components/ui/dict/Definition.vue'
import Example from '@/components/ui/dict/Example.vue'

export default {
  name: 'Item',
  props: {
    item: Object
  },
  components: {
    Definition,
    Example
  }
}
</script>

// src/components/Item.tsx
import React from 'react'
import { Definition as DefinitionType } from '../types/WordResult'
import Definition from './Definition'
import Example from './Example'

type ItemProps = {
  item: DefinitionType
}

const Item = (props: ItemProps) => {
  return (
    <>
      <Definition pos={props.item.pos} sense={props.item.sense} />
      <Example examples={props.item.examples}/>
    </>
  )
}

export default Item
