// src/components/ui/esdict/Item.vue
<template>
  <div>
    <EsDefinition
      :pos="item.pos"
      :sense="item.sense"
      />
    <EsExample
      :examples="item.examples"
      />
  </div>
</template>

<script>
import EsDefinition from '@/components/ui/esdict/Definition.vue'
import EsExample from '@/components/ui/esdict/Example.vue'

export default {
  name: 'EsItem',
  props: {
    item: Object
  },
  components: {
    EsDefinition,
    EsExample
  }
}
</script>

// src/components/Item.tsx
import React from 'react'
import { Definition as DefinitionType } from '../types/WordResult'
import Definition from './Definition'
import Example from './Example'

type ItemProps = {
  item: DefinitionType
}

const Item = (props: ItemProps) => {
  return (
    <>
      <Definition pos={props.item.pos} sense={props.item.sense} />
      <Example examples={props.item.examples}/>
    </>
  )
}

export default Item
